---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_CPANEL_USERNAME/public_html/
    - export REPOPATH=/home/YOUR_CPANEL_USERNAME/repositories/YOUR_REPO_NAME
    - /bin/cp -R $REPOPATH/dist/* $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/*
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \; 