---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pestne01/public_html/offer/
    - export REPOPATH=/home/pestne01/repositories/allguardlandingpage
    - /bin/cp -R $REPOPATH/dist/* $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/*
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \; 